basic: false 

samecondition: false 

random: false #uncurated 


interp: false 
interp_c:
  samples: 16
  n: 9




condscale: false # conduct visualization under different condition scale
condscale_c:
  range: [0, 0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  samples: 10

chainvis: false  # visualize chain 
chainvis_c: 
  samples: 7
  timestep: 7

tsne_vis: false #depreciated now
tsne_vis_c:
  cluster: 10

cluster_hist_vis: false #depreciated now


  